# Generated by Django 4.1 on 2022-08-18 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=models.ImageField(blank=True, default='profiles/user-default.png', null=True, upload_to='images/'),
        ),
    ]
