# Generated by Django 4.1 on 2022-08-18 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_post_post_img_alter_profile_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
