# Generated by Django 4.1 on 2022-08-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='another_user',
            field=models.ManyToManyField(blank=True, related_name='anotheruser', to='app.profile'),
        ),
    ]
