# Generated by Django 4.1 on 2022-08-18 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_profile_followers_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='followed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed_to', to='app.profile'),
        ),
    ]
