# Generated by Django 4.1 on 2022-08-18 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_follow_followed_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='followed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followedby', to='app.profile'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='followed_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followedto', to='app.profile'),
        ),
    ]
